const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/enquiry.controller');
const { protect } = require('../middleware/auth');
const { submitLimiter } = require('../middleware/rateLimiter');
router.post('/', submitLimiter, ctrl.submitEnquiry);
router.get('/', protect, ctrl.getAllEnquiries);
router.patch('/:id/status', protect, ctrl.updateEnquiryStatus);
router.delete('/:id', protect, ctrl.deleteEnquiry);
module.exports = router;
