const express = require('express');
const router = express.Router();
const ctrl = require('../controllers/testimonial.controller');
const { protect } = require('../middleware/auth');
router.get('/', ctrl.getFeaturedTestimonials);
router.get('/admin/all', protect, ctrl.getAllTestimonialsAdmin);
router.post('/', protect, ctrl.createTestimonial);
router.put('/:id', protect, ctrl.updateTestimonial);
router.delete('/:id', protect, ctrl.deleteTestimonial);
module.exports = router;
